# Generated by Django 5.2.14 on 2026-05-13 18:15

import django.db.models.deletion
from django.conf import settings
from django_mongodb_backend.fields import ObjectIdAutoField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(default=list, help_text='List of topics of interest')),
                ('tone', models.CharField(choices=[('gentle', 'Gentle & Nurturing'), ('bold', 'Bold & Empowering'), ('spiritual', 'Spiritual and Mindful')], max_length=20)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('obstacles', models.JSONField(default=list, help_text='What prevents you from achieving results?')),
                ('practice_time', models.CharField(choices=[('5min', '5 minutes a day'), ('10min', '10 minutes a day'), ('20min', '20 minutes a day')], max_length=10)),
                ('experience', models.CharField(choices=[('beginner', "I'm a total beginner"), ('few_times', "I've meditated a few times"), ('a_lot', 'I meditate a lot')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
