# Generated by Django 5.2.14 on 2026-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('x_profile_link', models.URLField(blank=True, null=True)),
                ('instagram_profile_link', models.URLField(blank=True, null=True)),
                ('facebook_profile_link', models.URLField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('about_glow', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
