# Generated by Django 5.2.14 on 2026-08-28 05:18

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/community/comment_images/', validators=[community.models.validate_comment_image_file]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/community/comment_videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/community/audio/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/community/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/community/post_videos/'),
        ),
    ]
