# Generated by Django 5.2.14 on 2026-08-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0002_adminotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
