"""
Django settings for HumanBackend project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import certifi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# SECURITY WARNING: keep the secret key used in production secret!


from dotenv import load_dotenv

# .env ফাইল লোড করা হচ্ছে
load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', 'HumanKind')
DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'django_mongodb_backend').lower()
MONGO_TLS = os.getenv('MONGO_TLS', 'True') == 'True'
MONGO_TLS_CA_FILE = os.getenv('MONGO_TLS_CA_FILE') or certifi.where()
MONGO_TLS_ALLOW_INVALID_CERTS = os.getenv('MONGO_TLS_ALLOW_INVALID_CERTS', 'False') == 'True'
MONGO_SERVER_SELECTION_TIMEOUT_MS = int(os.getenv('MONGO_SERVER_SELECTION_TIMEOUT_MS', '30000'))
MONGO_CONNECT_TIMEOUT_MS = int(os.getenv('MONGO_CONNECT_TIMEOUT_MS', '20000'))
MONGO_SOCKET_TIMEOUT_MS = int(os.getenv('MONGO_SOCKET_TIMEOUT_MS', '20000'))

# এখন আগের হার্ডকোড করা ভ্যালুগুলো পরিবর্তন করে এভাবে লিখুন:
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'

# Google Redirect URI settings.py এর নিচে যোগ করুন
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI')
SSL_COMMERZ_STORE_ID = os.getenv('STORE_ID')
SSL_COMMERZ_STORE_PASS = os.getenv('STORE_PASS')
SSL_COMMERZ_SANDBOX = os.getenv('SSL_COMMERZ_SANDBOX', 'True') == 'True'
SSL_COMMERZ_BASE_URL = 'https://sandbox.sslcommerz.com' if SSL_COMMERZ_SANDBOX else 'https://securepay.sslcommerz.com'
DAILY_AFFIRMATION_SERVICE_URL = os.getenv('DAILY_AFFIRMATION_SERVICE_URL', 'http://187.127.98.88:8050/api/daily_affirmation')
DAILY_AFFIRMATION_SERVICE_TIMEOUT = int(os.getenv('DAILY_AFFIRMATION_SERVICE_TIMEOUT', '240'))
AI_MEDITATION_SERVICE_URL = os.getenv('AI_MEDITATION_SERVICE_URL', 'http://187.127.98.88:8050/api/AI_Meditation')
AI_MEDITATION_SERVICE_TIMEOUT = int(os.getenv('AI_MEDITATION_SERVICE_TIMEOUT', '240'))
JOURNAL_SERVICE_URL = os.getenv('JOURNAL_SERVICE_URL', 'http://187.127.98.88:8050/api/journal')
JOURNAL_SERVICE_TIMEOUT = int(os.getenv('JOURNAL_SERVICE_TIMEOUT', '240'))

ALLOWED_HOSTS = ['https://nephelinitic-kaiden-instinctive.ngrok-free.dev/', 'localhost', '[IP_ADDRESS]', '*']   


# Application definition

INSTALLED_APPS = [
    'HumanBackend.mongo_app_configs.MongoAdminConfig',
    'HumanBackend.mongo_app_configs.MongoAuthConfig',
    'HumanBackend.mongo_app_configs.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'Authapp',
    'UserPersonalization',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'dj_rest_auth',
    'HumanBackend.mongo_app_configs.MongoSitesConfig',
    'allauth',
    'HumanBackend.mongo_app_configs.MongoAccountConfig',
    'HumanBackend.mongo_app_configs.MongoSocialAccountConfig',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
    'corsheaders',
    'community',
    'user_profile',
    'content',
    'subscriptions',
    'notifications',
    'progress',
    'admin_panel',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'HumanBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HumanBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DATABASE_ENGINE in {'sqlite', 'sqlite3', 'django.db.backends.sqlite3'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    mongo_options = {
        'serverSelectionTimeoutMS': MONGO_SERVER_SELECTION_TIMEOUT_MS,
        'connectTimeoutMS': MONGO_CONNECT_TIMEOUT_MS,
        'socketTimeoutMS': MONGO_SOCKET_TIMEOUT_MS,
    }

    if MONGO_TLS:
        mongo_options['tls'] = True
        mongo_options['tlsCAFile'] = MONGO_TLS_CA_FILE

    if MONGO_TLS_ALLOW_INVALID_CERTS:
        mongo_options['tlsAllowInvalidCertificates'] = True

    DATABASES = {
        'default': {
            'ENGINE': 'django_mongodb_backend',
            'HOST': MONGO_URI or '',
            'NAME': MONGO_DB_NAME,
            'OPTIONS': mongo_options,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

AUTH_USER_MODEL = 'Authapp.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SITE_ID = os.getenv('SITE_ID', '507f1f77bcf86cd799439011')

# SimpleJWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# dj-rest-auth settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt-refresh-auth',
}

# allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True # Change this for production


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
# Cloudinary settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
