# Generated by Django 5.2.14 on 2026-05-17 17:56

import django.db.models.deletion
from django.conf import settings
from django_mongodb_backend.fields import ObjectIdAutoField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='affirmations/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='meditations/thumbnails/')),
                ('audio_file', models.FileField(upload_to='meditations/audio/')),
                ('duration', models.CharField(help_text="e.g., '2 Min'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAffirmation',
            fields=[
                ('id', ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('affirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='content.affirmation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_affirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('affirmation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SavedMeditation',
            fields=[
                ('id', ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='content.meditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meditations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meditation', 'user')},
            },
        ),
    ]
