# Generated by Django 5.2.14 on 2026-08-15 10:10

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAffirmationCache',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_date', models.DateField(unique=True)),
                ('affirmation_text', models.TextField()),
                ('voice', models.TextField(blank=True, default='')),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cache_date', '-created_at'],
            },
        ),
    ]
