# Generated by Django 5.2.14 on 2026-08-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='HumanKind/affirmations/audio/'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='audio_file',
            field=models.FileField(upload_to='HumanKind/meditations/audio/'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='HumanKind/meditations/thumbnails/'),
        ),
    ]
