# Generated by Django 5.2.14 on 2026-05-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('alert', 'Alert'), ('subscription', 'Subscription Alert'), ('like', 'Like Alert'), ('comment', 'Comment Alert'), ('share', 'Share Alert')], default='info', max_length=20),
        ),
    ]
